<a href="https://colab.research.google.com/github/2303A52060/23CSBTB39-40/blob/main/assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

assignment-2,

name:m.bharath,

rollno:2303a52060.

Lab Exercise - Implement Breadth First, Depth First and A* Search
Algorithms

Part 1 -Implement Breadth First Search Algorithm using a Queue.

1. Given a graph with adjacency list and a starting vertex and we have to traverse the
graph.
2. We will first print the value in the starting vertex,
3. Continue to print the value of neighbors of the starting vertex and
4. Next move on to the next level after completing the current level till all the vertices of the graph are printed.



In [4]:
graph = {
    '0': ['1', '3'],
    '1': ['0', '2'],
    '2': ['1', '5'],
    '3': ['0', '4'],
    '4': ['3'],
    '5': ['2']
}
from collections import deque

def bfs(graph, start_vertex):

    queue = deque([start_vertex])


    visited = set()


    visited.add(start_vertex)

    while queue:

        vertex = queue.popleft()


        print(vertex)


        neighbors = graph.get(vertex, [])


        for neighbor in neighbors:
            if neighbor not in visited:

                queue.append(neighbor)
                visited.add(neighbor)

graph = {
    '0': ['1', '3'],
    '1': ['0', '2'],
    '2': ['1', '5'],
    '3': ['0', '4'],
    '4': ['3'],
    '5': ['2']
}

start_vertex = '0'

bfs(graph, start_vertex)


0
1
3
2
4
5


Part 2 – Implement Depth First Search Algorithm using a Stack.

DFS Stack implementations steps to be followed:

1. Start at the root node and push it onto the stack.

2. Check for any adjacent nodes of the tree and select one node.

3. Traverse the entire branch of the selected node and push all the nodes into the stack.

4. Upon reaching the end of a branch (no more adjacent nodes) ie nth leaf node, move
back by a single step and look for adjacent nodes of the n-1th node.

5. If there are adjacent nodes for the n-1th node, traverse those branches and push nodes onto the stack.


In [8]:
graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E'],
}
def dfs(graph, start_vertex):
    # Initialize a stack with the starting vertex
    stack = [start_vertex]

    # Set to keep track of visited vertices
    visited = set()

    while stack:
        # Pop a vertex from the stack
        vertex = stack.pop()

        if vertex not in visited:
            # Print the value of the vertex
            print(vertex)

            # Mark the vertex as visited
            visited.add(vertex)

            # Get the neighbors of the vertex and push them onto the stack
            # We reverse the neighbors to maintain the correct order of traversal
            neighbors = graph.get(vertex, [])
            for neighbor in reversed(neighbors):
                if neighbor not in visited:
                    stack.append(neighbor)

# Example graph represented as an adjacency list
graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E'],
}

# Starting vertex for DFS
start_vertex = 'A'

# Perform DFS
dfs(graph, start_vertex)


A
B
D
E
F
C


Part 3 – Implement A* Algorithm using Numpy.
1. A*Algorithm (pronounced as A-star) is a combination of ‘branch and bound search algorithm’ and ‘best search algorithm’ combined with the dynamic programming prin-ciple.

2. The A* Algorithm is well-known because it is used for locating path and graph traver-sals.

3. This algorithm is used in numerous online maps and games.

4. It uses a heuristic or evaluation function usually denoted by f(X) to determine the order in which the search visits nodes in the tree.



In [9]:
import numpy as np
import heapq

class Node:
    def __init__(self, state, parent=None):
        self.state = state
        self.parent = parent
        self.g = 0  # Cost from start to this node
        self.h = 0  # Heuristic cost from this node to goal
        self.f = 0  # Total cost

    def __eq__(self, other):
        return np.array_equal(self.state, other.state)

    def __lt__(self, other):
        return self.f < other.f

def manhattan_distance(state, goal_state):
    distance = 0
    for i in range(3):
        for j in range(3):
            value = state[i, j]
            if value != 0:
                goal_i, goal_j = np.where(goal_state == value)
                distance += abs(i - goal_i[0]) + abs(j - goal_j[0])
    return distance

def get_neighbors(state):
    neighbors = []
    zero_pos = np.argwhere(state == 0)[0]
    x, y = zero_pos
    directions = [(0, -1), (0, 1), (-1, 0), (1, 0)]  # Left, Right, Up, Down
    for dx, dy in directions:
        new_x, new_y = x + dx, y + dy
        if 0 <= new_x < 3 and 0 <= new_y < 3:
            new_state = np.copy(state)
            new_state[x, y], new_state[new_x, new_y] = new_state[new_x, new_y], new_state[x, y]
            neighbors.append(new_state)
    return neighbors

def astar(start_state, goal_state):
    start_node = Node(start_state)
    goal_node = Node(goal_state)

    open_list = []
    closed_list = set()

    heapq.heappush(open_list, start_node)

    while open_list:
        current_node = heapq.heappop(open_list)

        if current_node == goal_node:
            path = []
            while current_node:
                path.append(current_node.state)
                current_node = current_node.parent
            return path[::-1]

        closed_list.add(tuple(map(tuple, current_node.state)))

        for neighbor_state in get_neighbors(current_node.state):
            neighbor_node = Node(neighbor_state, current_node)
            if tuple(map(tuple, neighbor_node.state)) in closed_list:
                continue

            neighbor_node.g = current_node.g + 1
            neighbor_node.h = manhattan_distance(neighbor_node.state, goal_state)
            neighbor_node.f = neighbor_node.g + neighbor_node.h

            if any(neighbor_node == node and neighbor_node.f >= node.f for node in open_list):
                continue

            heapq.heappush(open_list, neighbor_node)

    return None

# Example start and goal states
start_state = np.array([
    [1, 2, 3],
    [4, 5, 0],
    [7, 8, 6]
])

goal_state = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
])

path = astar(start_state, goal_state)
for step in path:
    print(step)


[[1 2 3]
 [4 5 0]
 [7 8 6]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
