<a href="https://colab.research.google.com/github/2303A52060/23CSBTB39-40/blob/main/sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Python program for
# Creation of Arrays
import numpy as np

 # Creating a rank 1 Array
array = np.array([1, 2, 3])
print("array with Rank 1: \n",array)

  # Creating a rank 2 Array
array = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("array with Rank 2: \n", array)

# Creating an array from tuple
array = np.array((1, 3, 2))
print("\nArray created using "
"passed tuple:\n", array)


array with Rank 1: 
 [1 2 3]
array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [10]:
import numpy as np

# Create matrices from lists
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Create an identity matrix
I = np.eye(3)  # 3x3 identity matrix

# Create matrices of zeros and ones
zeros_matrix = np.zeros((2, 3))  # 2x3 matrix of zeros
ones_matrix = np.ones((3, 2))    # 3x2 matrix of ones

# Create a diagonal matrix
diag_matrix = np.diag([1, 2, 3])  # Diagonal matrix with diagonal elements 1, 2, 3
# Matrix addition and subtraction
C = A + B
D = A - B

# Element-wise multiplication
E = A * B

# Matrix multiplication (dot product)
F = np.dot(A, B)  # Or equivalently, A @ B
# Transpose a matrix
A_T = np.transpose(A)
# Or equivalently:
A_T = A.T
# Invert a matrix (if it's square and invertible)
A_inv = np.linalg.inv(A)

# Check if a matrix is invertible
is_invertible = np.linalg.det(A) != 0
# Calculate the determinant
det_A = np.linalg.det(A)

# Calculate the trace (sum of diagonal elements)
trace_A = np.trace(A)
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
# Perform SVD
U, S, Vh = np.linalg.svd(A)

# S is returned as a 1D array of singular values, to get the diagonal matrix:
S_matrix = np.diag(S)
# Calculate different norms
norm_F = np.linalg.norm(A, 'fro')  # Frobenius norm
norm_2 = np.linalg.norm(A, 2)      # Spectral norm (largest singular value)
# Solve the system of linear equations Ax = b
b = np.array([1, 1])
x = np.linalg.solve(A, b)
# Reshape matrices
reshaped_A = np.reshape(A, (4, 1))  # Reshape to 4x1 matrix

# Resize matrices
resized_A = np.resize(A, (3, 2))  # Resize to 3x2 matrix
# Concatenate matrices
concat_horizontal = np.hstack((A, B))
concat_vertical = np.vstack((A, B))

# Split matrices
split_horizontal = np.hsplit(A, 2)
split_vertical = np.vsplit(A, 2)
# Calculate the rank of a matrix
rank_A = np.linalg.matrix_rank(A)

import numpy as np

# Create matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Basic operations
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("A + B:")
print(A + B)
print("A - B:")
print(A - B)
print("A * B (element-wise):")
print(A * B)
print("A @ B (matrix multiplication):")
print(np.dot(A, B))

# Transpose
print("Transpose of A:")
print(A.T)

# Inverse
try:
    print("Inverse of A:")
    print(np.linalg.inv(A))
except np.linalg.LinAlgError:
            print("Matrix A is not invertible")

            # Determinant and trace
            print("Determinant of A:")
            print(np.linalg.det(A))
            print("Trace of A:")
            print(np.trace(A))

            # Eigenvalues and eigenvectors
            eigenvalues, eigenvectors = np.linalg.eig(A)
            print("Eigenvalues of A:")
            print(eigenvalues)
            print("Eigenvectors of A:")
            print(eigenvectors)

            # Singular Value Decomposition
            U, S, Vh = np.linalg.svd(A)
            print("U from SVD:")
            print(U)
            print("Singular values from SVD:")
            print(S)
            print("Vh from SVD:")
            print(Vh)

            # Norms
            print("Frobenius norm of A:")
            print(np.linalg.norm(A, 'fro'))
            print("Spectral norm of A:")
            print(np.linalg.norm(A, 2))

            # Solving a linear system
            b = np.array([1, 1])
            print("Solution to Ax = b:")
            print(np.linalg.solve(A, b))

            # Reshape and resize
            print("Reshape A to (4,1):")
            print(np.reshape(A, (4, 1)))
            print("Resize A to (3,2):")
            print(np.resize(A, (3, 2)))

            # Concatenation and splitting
            print("Horizontal concatenation of A and B:")
            print(np.hstack((A, B)))
            print("Vertical concatenation of A and B:")
            print(np.vstack((A, B)))
            print("Split A horizontally:")
            print(np.hsplit(A, 2))
            print("Split A vertically:")
            print(np.vsplit(A, 2))

            # Rank
            print("Rank of A:")
            print(np.linalg.matrix_rank(A))


Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
A + B:
[[ 6  8]
 [10 12]]
A - B:
[[-4 -4]
 [-4 -4]]
A * B (element-wise):
[[ 5 12]
 [21 32]]
A @ B (matrix multiplication):
[[19 22]
 [43 50]]
Transpose of A:
[[1 3]
 [2 4]]
Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]
